name: moldesign_env
channels:
 - omnia
dependencies:
 - python=2.7
 - biopython
 - markdown2
 - matplotlib
 - numpy
 - parmed >= 2.0.0
 - pint >= 0.7
 - pytest
 - pyyaml
 - requests
 - scipy
 - "openbabel>=2.3,<2000"  # don't use old versions that were marked as "2015.X.Y"
 - openmm
 - pip:
   - ipython
   - ipykernel!=4.5.1
   - notebook
   - webcolors
   - funcsigs
   - docker-py
   - fortranformat
   - pyccc >= 0.6.7a0
   - ipywidgets >= 5.1
   - nbmolviz == 0.6.7rc2  # increment for release as appropriate
